spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/site1_prod
    username: lldjlocal
    password: 1234
custom:
  site:
    front_url: https://localhost:3000
    back_url: https://api.topcating.bdkms.com:8080
